export enum ServerErrorCode {
  // Generics
  EC_SUCCESS = 0,
  EC_GENERIC_ERROR = 1,
  EC_INTERNAL_ERROR = 2,

  // Argument Error
  EC_ARG_GENERIC_ERROR = 100,
  EC_ARG_INVALID_ERROR = 101,
  EC_ARG_NOUSERNAME_ERROR = 102,
  EC_ARG_NOEMAIL_BUT_HASPASSWD_ERROR = 103,

  // Database Error
  EC_DB_GENERIC_ERROR = 200,
  EC_DB_NOT_FOUND_ERROR = 201,
  
  // User Error
  EC_USER_GENERIC_ERROR = 300,

  EC_USER_REG_ERROR = 301,
  EC_USER_REG_DUP_NAME_ERROR = 302,
  EC_USER_REG_DUP_EMAIL_ERROR = 303,
  EC_USER_REG_DUP_BOTH_NAME_EMAIL_ERROR = 304,

  EC_USER_LOGIN_ERROR = 350,
  EC_USER_LOGIN_TOKEN_EXPIRED = 351,
  EC_USER_LOGIN_TOKEN_SIGN_ERROR = 352,

  EC_USER_UNAUTHORIZED_ERROR = 399,
}